# Generated by Django 3.2.8 on 2023-08-30 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
